//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyContext : DbContext
    {
        public MyContext()
            : base("name=MyContext")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<tblAdressRoom> tblAdressRoom { get; set; }
        public virtual DbSet<tblCities> tblCities { get; set; }
        public virtual DbSet<tblDistricts> tblDistricts { get; set; }
        public virtual DbSet<tblRoomImages> tblRoomImages { get; set; }
        public virtual DbSet<tblRooms> tblRooms { get; set; }
        public virtual DbSet<tblStreets> tblStreets { get; set; }
    }
}
