//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRooms()
        {
            this.tblAdressRoom = new HashSet<tblAdressRoom>();
            this.tblRoomImages = new HashSet<tblRoomImages>();
        }
    
        public int Id { get; set; }
        public decimal Price { get; set; }
        public int Floor { get; set; }
        public int CountRooms { get; set; }
        public decimal Square { get; set; }
        public bool Reserved { get; set; }
        public bool Sales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdressRoom> tblAdressRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoomImages> tblRoomImages { get; set; }
    }
}
